version: '3.1'

services:
  mongodb:
    container_name: mongodb-container
    image: mongo:4.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_USERNAME="${MONGODB_USER}"
      - MONGODB_PASSWORD="${MONGODB_PASSWORD}"
      - MONGODB_DATABASE=mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/bitnami/mongodb
    networks:
      - gis-dl-local-network      

volumes:
  mongodb_data:
    driver: local

networks:
  gis-dl-local-network:
    external: true    
